name: CI

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.6.10

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: pnpm run build
